/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnchorTool: typeof import('./src/components/PageTool/AnchorTool/AnchorTool.vue')['default']
    Aside: typeof import('./src/components/Layout/Aside.vue')['default']
    DownloadTool: typeof import('./src/components/PageTool/Down_Lang/DownloadTool.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Iconfont: typeof import('./src/components/Iconfont/Iconfont.vue')['default']
    Index: typeof import('./src/components/PageTool/Down_Lang/Index.vue')['default']
    ListWrap: typeof import('./src/components/ListWrap/ListWrap.vue')['default']
    Main: typeof import('./src/components/Layout/Main.vue')['default']
    ProjectWrap: typeof import('./src/components/ProjectWrap/ProjectWrap.vue')['default']
    RepositoryItem: typeof import('./src/components/RepositoryItem/RepositoryItem.vue')['default']
    RowContent: typeof import('./src/components/RowContent/RowContent.vue')['default']
    Section: typeof import('./src/components/Layout/Section.vue')['default']
    TaggleLang: typeof import('./src/components/PageTool/Down_Lang/TaggleLang.vue')['default']
    ThemeChange: typeof import('./src/components/PageTool/ThemeChange/ThemeChange.vue')['default']
    TitleDesc: typeof import('./src/components/TitleDesc/TitleDesc.vue')['default']
  }
}
